### ISSUE TITLE
Make entry points

### ISSUE THREAD

**Issue by tiagocoutinho** [tiagocoutinho/sinstruments#4]
* Instrument Simulator version: >= 1
* Python version: any
* Operating System: any

### Description

It would be nice if sinstruments is able to recognize entry points corresponding to external projects.
Right now, to load a simulator from external project (ex: [GE Pace](https://github.com/tiagocoutinho/gepace)) you need to write the following configuration:
```yaml
devices:
- class: Pace
  package: gepace.simulator
  transports:
  - type: tcp
    url: :5000
```

with an entry point we can simplify to:

```yaml
devices:
- class: Pace
  transports:
  - type: tcp
    url: :5000
```

Other benefits:

* standardize the way third-party libraries register their simulators
* easy to write a `sinstruments-server ls` command to list all registered simulators
* cleanup boiler plate code which searches for simulators in the simulators sub-directory

### What I Did

So far, discussed the idea with @rhomspuron
